# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df56f3255fdf965c85d818ea7feb612a6f12a17523962aa1c9b9fbfae414efaf236a80e40baa2f322338f4da1bfe8b72bdd2c13197d2b0cb4f096c6e3749d4a

test:
  secret_key_base: 1df20d4b700c57073324808745ecf04618d42c82bd9d17e0914b5e7eb6d340c1a81c227bdd53b3f2bdcd37c65378083e21a132dadf1c72bb7e14407fc56fcd32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
